In [99]:
import pandas as pd
from pprint import pprint

In [100]:
df = pd.read_csv("random_zip_codes.csv")

In [101]:
# Get quantity of duplicates via pivot table.
duplicates = df.pivot_table(index=["zip"], aggfunc='size')

In [102]:
# Turn duplicates into a new data frame.
df = duplicates.reset_index()

In [103]:
df.rename(columns={0:'quantity'}, inplace=True)

In [104]:
df

     zip  quantity
0  15859         1
1  21279         2
2  22965         1
3  35279         7
4  37345         6
5  55122         1
6  56769         1
7  76698         1
8  83224         1
9  94336         1

In [105]:
df.to_csv("aggregated_locations_of_users.csv", index=False)

In [106]:
# Open a aggregated set of random zip codes.
df = pd.read_csv("aggregated_locations_of_users.csv", converters={"zip": lambda x: str(x)})

In [107]:
# Open prepared registry of zip codes.
df2 = pd.read_csv("prepared_registry_german_zip_codes.csv", converters={'postal code': lambda x: str(x)}, )

In [108]:
df2

,country code,postal code,place name,admin name1,admin code1,admin name2,admin code2,admin name3,admin code3,latitude,longitude,accuracy
0,DE,01945,Guteborn,Brandenburg,BB,NaN,0.0,Landkreis Oberspreewald-Lausitz,12066.0,51.4167,13.9333,4.0
1,DE,01945,Hohenbocka,Brandenburg,BB,NaN,0.0,Landkreis Oberspreewald-Lausitz,12066.0,51.4310,14.0098,4.0
2,DE,01945,Kroppen,Brandenburg,BB,NaN,0.0,Landkreis Oberspreewald-Lausitz,12066.0,51.3833,13.8000,4.0
3,DE,01945,Lindenau,Brandenburg,BB,NaN,0.0,Landkreis Oberspreewald-Lausitz,12066.0,51.4000,13.7333,4.0
4,DE,01945,Grünewald,Brandenburg,BB,NaN,0.0,Landkreis Oberspreewald-Lausitz,12066.0,51.4000,14.0000,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...
16473,DE,99996,Obermehler,Thüringen,TH,NaN,0.0,Unstrut-Hainich-Kreis,16064.0,51.2700,10.5975,4.0
16474,DE,99996,Menteroda,Thüringen,TH,NaN,0.0,Unstrut-Hainich-Kreis,16064.0,51.3076,10.5632,4.0
16475,DE,99998,Mühlhausen/Thüringen,Thüringen,TH,NaN,0.0,Unstrut-Hainich-Kreis,16064.0,51.1917,10.5250,4.0
16476,DE,99998,Körner,Thüringen,TH,NaN,0.0,Unstrut-Hainich-Kreis,16064.0,51.2333,10.6000,4.0
16477,DE,87491,Jungholz,NaN,NaN,NaN,NaN,NaN,NaN,47.5741,10.4472,NaN

In [109]:
# Function to match aggregated set of random zip codes with prepared zip code registry. Returns mean coordinates.
def check_file(x):
    mask = df2["postal code"].str.contains(x)
    # Sometimes there are several loactions associated with one zip. We calculate mean coordinates.
    longitude = df2[mask]["longitude"].mean()
    latitude = df2[mask]["latitude"].mean()
    return longitude, latitude

In [110]:
# Assigns coordinates as new columns to set of random zip codes.
df["av. longitude"], df["av. latitude"] = zip(*df["zip"].apply(check_file))

In [111]:
# Works!
df

     zip  quantity  av. longitude  av. latitude
0  15859         1      13.894806     52.227569
1  21279         2       9.748000     53.359325
2  22965         1      10.347800     53.694600
3  35279         7       9.116700     50.850000
4  37345         6      10.434645     51.518855
5  55122         1       8.237000     49.995000
6  56769         1       7.004175     50.279150
7  76698         1       8.631600     49.163000
8  83224         1      12.468450     47.782150
9  94336         1      12.739750     48.946450

In [112]:
df.to_csv("random_zip_codes_with_coordinates.csv", index=False)